name : First GitHub WF

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v7

          - name: Welcom Message
            run: echo "My First Workflow"

          - name: Install Cowsay Program
            run: sudo apt-get install cowsay -y
            
          - name: List all files
            run: | 
                ls
                ls -ltra
          - name: Generate ASCII Network
            run: cowsay -f dragon "Run for cover, Hi abdo" >> dragon.txt 

          - name: Read File
            run: cat dragon.txt
          

    ascii_job:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v7

        - name: Executing Shell Script
          run: | 
                cd .github/workflows
                chmode +x ascii_script.sh
                ./ascii_script.sh