name : First GitHub WF

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:

          - name: Checkout Repo
            use: actions/checkout@v7

          - name: Welcom Message
            run: echo "My First Workflow"

          - name: List files
            run: ls 

          - name: Read File
            run: cat README.md